orbs:
  ssh-deployment: singularitynet/ssh-deployment@1.1.20
version: 2.1
workflows:
  deploy_application:
    jobs:
      - ssh-deployment/deploy:
          ssh-host: 192.168.125.130
          ssh-user: mlc
          git-repo: convert-to-md
          git-branch: deploy
          mainnet-port: '7000'
          run-command: ll

