version: 2.1

jobs:
  build-deploy:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "${FINGER_PRINT}"
      - checkout
      - run:
          name: Run shell file for build and deploy
          command: ./script/deploy.sh

workflows:
  main:
    jobs:
      - build-deploy

deployment:
  production:
    branch: develop
    commands:
      - scp -r convert-to-md/* mlc@192.168.125.129:/home/mlc/hugoSites/deploy.hugo.github.io/convert-to-md
