version: 2.1

jobs:
  build-deploy:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "${FINGER_PRINT}"
      - checkout
      - run:
          name: Run shell file for build and deploy
          command: |
            ./script/deploy.sh
            python github_sync.py
  sync:
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run:
          name: Github Sync
          command: python github_sync.py
workflows:
  main:
    jobs:
      - build-deploy
      - sync:
          requires:
            - build-deploy
