version: 2.1

jobs:
  build-deploy:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "${FINGER_PRINT}"
      - checkout
      - run:
          name: Run shell file for build and deploy
          command: ./script/deploy.sh
  run:
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run:
          name: Run
          command: ./script/deploy.sh
workflows:
  main:
    jobs:
      - build-deploy
      - run:
          requires:
            - build-deploy
