version: 2.1

jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "${FINGER_PRINT}"
      - checkout
      - run:
          name: Run shell file for build and deploy
          command: ./script/deploy.sh
  deploy:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - add_ssh_keys:
          fingerprints:
            - "${FINGER_PRINT}"
      - run:
          name: Deploy in Local
          command: |
            ufw allow ssh
            ssh  mlc@192.168.125.1 -p 56924

workflows:
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
