version: 2.1

jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "${FINGER_PRINT}"
      - checkout
      - run:
          name: Run shell file for build and deploy
          command: ./script/deploy.sh
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "${FINGER_PRINT}"
      - run:
          name: Deploy in Local
          command: |
            ssh mlc@192.168.125.129 "git pull origin deploy"

workflows:
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
